


export interface ImarketUserInfo{
  "username"?:string,
  "name"?:string,
  "mobile"?:string,
  "zipcode"?:string,
  "idcard"?:string,
  "nickname"?:string,
  "email"?:string,
  "sex"?:string,
  "mybirthday"?:string,
  "year"?:string,
  "month"?:string,
  "day"?:string,
  "province"?:string,
  "city"?:string,
  "area"?:string,
  "marital_status"?:string,
  "address"?:string,
  "avatar"?:string,
  "education"?:string,
  "house"?:string,
  "car"?:string,
  "category"?:string,
  "verified"?:string,
  "id_card_auditinfo"?:string,
  "companyName"?:string,
  "license_num"?:string,
  "create_time"?:string,
  "companyAddress"?:string,
  "totalprice"?:string,
  "currency"?:string,
  "identification"?:string,
  "double_authentication"?: boolean,
  "is_transaction_pwd"?: boolean,
  "hasPayPwd"?:string,
  "imgUrl"?:string,
  "authState"?:string,
  "wait_pay"?:number,
  "wait_recv"?:number

}
